//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EE300Project.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EE300Project.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7020
        ///7020
        ///7020
        ///7020
        ///7020
        ///7020
        ///7020
        ///7000
        ///7000
        ///7920
        ///7920
        ///6700
        ///8400
        ///7920
        ///8400
        ///5500
        ///5500
        ///5500
        ///5500
        ///5500
        ///5500
        ///5500
        ///5500
        ///5525
        ///6150
        ///6900
        ///5500
        ///7600
        ///6400
        ///6400
        ///6400
        ///6400
        ///6400
        ///6400
        ///8500
        ///8800
        ///6600
        ///5500
        ///5500
        ///5500
        ///8400
        ///8400
        ///7020
        ///7020
        ///7020
        ///7900
        ///5500
        ///8400
        ///6900
        ///8000
        ///8200
        ///8200
        ///5500
        ///5500
        ///5500
        ///5500
        ///6770
        ///8300
        ///8800
        ///8800
        ///8800
        ///8600
        ///8800
        ///5500
        ///6238
        ///8500
        ///8000
        ///8000
        ///8800
        ///8400
        ///8400
        ///7300
        ///7986
        ///7920
        ///7920
        ///7920
        ///7920
        ///7020
        ///7315
        ///5500
        ///7020
        ///8250
        ///6250
        ///5400
        ///5400
        ///77 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EverestDeathList {
            get {
                return ResourceManager.GetString("EverestDeathList", resourceCulture);
            }
        }
    }
}
